language: python

sudo: false

python:
  - "2.7"
  - "3.4"

env:
  - DJANGO_VERSION=1.11.0

install:
  - travis_retry pip install detox tox-travis coverage coveralls
  - pip install -r requirements.django-"$TRAVIS_PYTHON_VERSION".txt --quiet

script:
  - python ./runtests.py
  - coverage run --source=drfs ./runtests.py

after_success:
  - coveralls
